name: Prescott Arizona Great Outdoors
favicon: null
layout_spectrum: 0.6274076108820736
typography_spectrum: 0.46358038391917944
title: Prescott AZ Outdoors in Pictures and Print
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02153f'
    - '#f5edda'
    - '#888981'
    - '#c0bd9f'
    - '#e77f10'
  brandStrength: 0.38447152939625084
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
